name: Go
on:
    push:
        branches:
            - $default-branch
    pull_request:
        branches:
            - $default-branch
    workflow_dispatch: {}
jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - run: sudo apt install tk-dev xvfb -y --no-install-recommends
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.21'
            - run: go build -v ./...
            - run: xvfb-run go test -v ./...

